### ISSUE TITLE
False positive for emails

### ISSUE THREAD

**Issue by azertys** [voku/anti-xss#44]
Hello, 

I have an issue where an email would be considered dangerous when enclosed between `<>` tags. For example: 

`<styler_tester@gmail.com>`. It's basically <$keyword(*.)@gmail.com> where $keyword is something that would be considered the start of a dangerous tag like style, script etc.

What happens is that the tags are encoded like `&lt;` and `&gt;` causing the content to be double escaped in my case. Any ideas how to fix this behaviour or if it is possible at all?

Thanks!

**Comment by voku** [comment]
fixed in version 4.1.11

**Comment by azertys** [comment]
@voku I'm not sure if this is considered correct but it doesn't fully work as expected. Iterating through the list of `$_evil_html_tags` some values are still getting stripped.

Culprits are:
`<audio@gmail.com` becomes `<audio@`
`<video@gmail.com` becomes `<video@`
`<source@gmail.com` becomes `<source@`
`<script@gmail.com` becomes ``

**Comment by voku** [comment]
@azertys ```_remove_disallowed_javascript``` was the problem here, fixed via https://github.com/voku/anti-xss/commit/1e43e5173a93a1bd42d8cdfd58fec9b19acd16e5

fixed in version 4.1.12

**Comment by azertys** [comment]
@voku Thanks! Seems to work now except for the `<script@gmail.com>` part which is still stripped to an empty string.  In my previous example I forgot to include the closing tag.

**Comment by voku** [comment]
fixed in version 4.1.13 :+1:

**Comment by azertys** [comment]
@voku Thank you! Works great now.
